### ISSUE TITLE
[epic] order and information

### ISSUE THREAD

**Issue by mckaygerhard** [my-garbage-stuff/alpine-xfce#1]
hi @sulincix in your profile you put that dont use github but i do not see the same repo of "alpine-kde" in gitlab..

also apart of the gitlab dependency, the repository doe snot have a documentation of tecnical details.. 

- [ ] Some info of the repository in gitlab? or is github the only one?
- [ ] Some minimal information
    - [ ]  of the usage, 
    - [ ] technical details of the workflow
    - [ ] dependency and runtime needs
- [ ] What is purposed of thia? What is for this?

**Comment by mckaygerhard** [comment]
where is the comleted task of those? @sulincix  .. seems that all the related project has no great informatin neither order, README are missing etc etc etc, in fact the only good documentation is the teaiso made by me
